In [28]:
import tensorflow as tf
import numpy as np

In [29]:
# Create Tensorflow Variables
const = tf.Variable(2.0, name='const')
b = tf.Variable(2.0, name='b')
c = tf.Variable(1.0, name='c')

In [30]:
const

<tf.Variable 'const:0' shape=() dtype=float32, numpy=2.0>

In [31]:
# Now create some operations
d = tf.add(b,c, name='d')
e = tf.add(c,const, name ='e')
a = tf.multiply(d,e,name='a')

In [32]:
print(f"Variable a is {a.numpy()}")

Variable a is 9.0


In [33]:
# Now making b an array
b = tf.Variable(np.arange(0,10), name='b')
b

<tf.Variable 'b:0' shape=(10,) dtype=int64, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [34]:
d = tf.cast(b, tf.float32) + c
d

<tf.Tensor: shape=(10,), dtype=float32, numpy=array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)>

In [35]:
e = tf.add(c,const, name ='e')
a = tf.multiply(d,e,name='a')

In [36]:
# a
a.numpy()

array([ 3.,  6.,  9., 12., 15., 18., 21., 24., 27., 30.], dtype=float32)

In [37]:
# b[1].assign(10) #In TensorFlow, the developer can do the same thing but must use the assign operation like so:
# b[6:9].assign([10,10,10]) #The developer could also run the following, to assign a slice of b values
f = b[2:5] #A new tensor can also be created by using the slice notation
f

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([2, 3, 4])>